/* Calculate total revenue generated by customer purchases */

SELECT 
    SUM(quantity * cost_to_customer_per_qty) AS total_revenue 
FROM farmers_market.customer_purchases;

/*
* Explanation:
* SUM(quantity * cost_to_customer_per_qty): Computes the total revenue by multiplying quantity with cost per unit.
* This query provides the total earnings from all customer purchases.
*/
